apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hptihqw2y-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hptihqw2y-java-springboot-gitops