apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hptihqw2y-java-springboot
  janus-idp.io/tekton: hptihqw2y-java-springboot
  backstage.io/kubernetes-id: hptihqw2y-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hptihqw2y-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
